
CC = gcc
CFLAGS = -g -Wall 
EJS = Ejercicio2 Ejercicio4 Ejercicio6a Ejercicio6b Ejercicio9
######################################################################################################################################

all: $(EJS)

Ejercicio2:
	$(CC) $(CFLAGS) Ejercicio2.c -o Ejercicio2

Ejercicio4:
	$(CC) $(CFLAGS) Ejercicio4.c -o Ejercicio4

Ejercicio6a:
	$(CC) $(CFLAGS) Ejercicio6a.c -o Ejercicio6a

Ejercicio6b:
	$(CC) $(CFLAGS) Ejercicio6b.c -o Ejercicio6b

Ejercicio9:
	$(CC) $(CFLAGS) Ejercicio9.c Ejercicio8.h Ejercicio8.c -o Ejercicio9


clean:
	rm -rf *o. $(EJS)