
CC = gcc
CFLAGS = -g -Wall 
EJS = Ejercicio4 Ejercicio5a Ejercicio5b Ejercicio6 Ejercicio6_dem Ejercicio8 Ejercicio9 Ejercicio12a Ejercicio12b Ejercicio13 Ejercicio13b
######################################################################################################################################

all: $(EJS)

Ejercicio4:
	$(CC) $(CFLAGS) Ejercicio4.c -o Ejercicio4

Ejercicio5a:
	$(CC) $(CFLAGS) Ejercicio5a.c -o Ejercicio5a

Ejercicio5b:
	$(CC) $(CFLAGS) Ejercicio5b.c -o Ejercicio5b

Ejercicio6:
	$(CC) $(CFLAGS) Ejercicio6.c -o Ejercicio6

Ejercicio6_dem:
	$(CC) $(CFLAGS) Ejercicio6_dem.c -o Ejercicio6_dem

Ejercicio8:
	$(CC) $(CFLAGS) Ejercicio8.c -o Ejercicio8

Ejercicio9:
	$(CC) $(CFLAGS) Ejercicio9.c -o Ejercicio9 -lm

Ejercicio11:
	$(CC) $(CFLAGS) Ejercicio11.c -o Ejercicio11 -lpthread

Ejercicio12a:
	$(CC) $(CFLAGS) Ejercicio12a.c -o Ejercicio12a -lpthread -lm

Ejercicio12b:
	$(CC) $(CFLAGS) Ejercicio12b.c -o Ejercicio12b -lpthread -lm

Ejercicio13:
	$(CC) $(CFLAGS) Ejercicio13.c -o Ejercicio13 -lpthread

Ejercicio13b:
	$(CC) $(CFLAGS) Ejercicio13b.c -o Ejercicio13b -lpthread


clean:
	rm -rf *o. $(EJS)